services:
  - type: web
    name: automatic-meal-analysis
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: APP_PASSWORD
        sync: false
      - key: NICEGUI_STORAGE_SECRET
        generateValue: true
